version: '3.9'
services:

  pay-my-buddy:
    build: .
    image: loutix/pay-my-buddy
    container_name: paymybuddy_container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mariadb://database_mariadb:3306/pay_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - database_mariadb
    networks:
      - pay-network

  database_mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pay_app
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - pay-network

volumes:
  db-data:

    #*********** NETWORK ***********
networks:
  pay-network:
    driver: bridge