services:

  #*********** MARIA DB ***********
  paymybuddy:
    image: loutix/paymybuddy:latest
    container_name: paymybuddy
    restart: always
    environment:
      - spring.datasource.url=j${DB_HOST}
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}
    networks:
      - applications-network

  #*********** NETWORK ***********
networks:
  applications-network:
    driver: bridge